# Generated by Django 5.2.13 on 2026-05-21 08:21

import django.core.validators
import django.db.models.deletion
import netbox.models.deletion
import taggit.managers
import utilities.json
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dcim', '0227_alter_interface_speed_bigint'),
        ('extras', '0134_owner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(default='draft', max_length=30)),
                ('planned_date', models.DateField()),
                ('reason', models.CharField(max_length=500)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_access_requests', to=settings.AUTH_USER_MODEL)),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='access_request', to='dcim.region')),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='access_request', to='dcim.site')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'verbose_name': 'Access Request',
                'verbose_name_plural': 'Access Requests',
                'ordering': ('-last_updated',),
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name='AccessRequestHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=50)),
                ('status', models.CharField(default='success', max_length=50)),
                ('description', models.TextField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('access_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='histories', to='access_request_management.accessrequest')),
                ('perform_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_request_histories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Access Request History',
                'verbose_name_plural': 'Access Request Histories',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='AccessRequestPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('identity_code', models.CharField(max_length=12, validators=[django.core.validators.RegexValidator(message='Identity code must contain exactly 12 digits.', regex='^\\d{12}$')])),
                ('full_name', models.CharField(max_length=50)),
                ('organization', models.CharField(max_length=100)),
                ('job_title', models.CharField(blank=True, max_length=50)),
                ('phone_number', models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator(message='Enter a valid Vietnamese phone number (10 digits, starting with 0).', regex='^0\\d{9}$')])),
                ('description', models.TextField(blank=True, max_length=500)),
                ('access_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='persons', to='access_request_management.accessrequest')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='access_request_members', to='dcim.location')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'verbose_name': 'Access Request Member',
                'verbose_name_plural': 'Access Request Members',
                'ordering': ('full_name',),
                'constraints': [models.UniqueConstraint(fields=('access_request', 'identity_code'), name='unique_access_request_identity_code')],
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
    ]
