# Generated by Django 5.2.13 on 2026-05-21 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('access_request_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accessrequestperson',
            options={'ordering': ('last_updated',)},
        ),
    ]
