# Generated by Django 5.2.13 on 2026-05-22 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_request_management', '0002_alter_accessrequestperson_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessrequestperson',
            name='status',
            field=models.CharField(default='pending', max_length=50),
        ),
    ]
