# Generated by Django 5.2.13 on 2026-05-27 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_request_management', '0003_accessrequestperson_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessrequestperson',
            name='entry_status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
